from pathlib import Path

from scripts.day0.bootstrap_servicefabric_runtime import digest_tree


def test_package_digest_ignores_generated_build_metadata(tmp_path: Path) -> None:
    package = tmp_path / "risk_example"
    source = package / "src" / "risk_example" / "module.py"
    source.parent.mkdir(parents=True)
    source.write_text("VALUE = 1\n", encoding="utf-8")
    (package / "pyproject.toml").write_text("[project]\nname = 'risk-example'\n", encoding="utf-8")
    reviewed_digest = digest_tree((package,))

    egg_info = package / "src" / "risk_example.egg-info"
    egg_info.mkdir()
    (egg_info / "PKG-INFO").write_text("generated metadata\n", encoding="utf-8")
    build_copy = package / "build" / "lib" / "risk_example" / "module.py"
    build_copy.parent.mkdir(parents=True)
    build_copy.write_text("VALUE = 1\n", encoding="utf-8")
    cache = source.parent / "__pycache__"
    cache.mkdir()
    (cache / "module.cpython-311.pyc").write_bytes(b"generated bytecode")

    assert digest_tree((package,)) == reviewed_digest


def test_package_digest_changes_with_source(tmp_path: Path) -> None:
    package = tmp_path / "risk_example"
    source = package / "src" / "risk_example" / "module.py"
    source.parent.mkdir(parents=True)
    source.write_text("VALUE = 1\n", encoding="utf-8")
    reviewed_digest = digest_tree((package,))

    source.write_text("VALUE = 2\n", encoding="utf-8")

    assert digest_tree((package,)) != reviewed_digest
