from pathlib import Path
import json

from scripts.day0.bootstrap_servicefabric_runtime import digest_tree
from scripts.day1.bootstrap_servicefabric_runtime import LOCAL_PACKAGE_NAMES


ROOT = Path(__file__).resolve().parents[2]


def test_package_digest_ignores_generated_build_metadata(tmp_path: Path) -> None:
    package = tmp_path / "risk_example"
    source = package / "src" / "risk_example" / "module.py"
    source.parent.mkdir(parents=True)
    source.write_text("VALUE = 1\n", encoding="utf-8")
    (package / "pyproject.toml").write_text("[project]\nname = 'risk-example'\n", encoding="utf-8")
    reviewed_digest = digest_tree((package,))

    egg_info = package / "src" / "risk_example.egg-info"
    egg_info.mkdir()
    (egg_info / "PKG-INFO").write_text("generated metadata\n", encoding="utf-8")
    build_copy = package / "build" / "lib" / "risk_example" / "module.py"
    build_copy.parent.mkdir(parents=True)
    build_copy.write_text("VALUE = 1\n", encoding="utf-8")
    cache = source.parent / "__pycache__"
    cache.mkdir()
    (cache / "module.cpython-311.pyc").write_bytes(b"generated bytecode")

    assert digest_tree((package,)) == reviewed_digest


def test_package_digest_changes_with_source(tmp_path: Path) -> None:
    package = tmp_path / "risk_example"
    source = package / "src" / "risk_example" / "module.py"
    source.parent.mkdir(parents=True)
    source.write_text("VALUE = 1\n", encoding="utf-8")
    reviewed_digest = digest_tree((package,))

    source.write_text("VALUE = 2\n", encoding="utf-8")

    assert digest_tree((package,)) != reviewed_digest


def test_day1_hosted_runtime_uses_the_complete_reviewed_package_set() -> None:
    assert LOCAL_PACKAGE_NAMES == (
        "risk_domain",
        "risk_planning",
        "risk_data",
        "risk_capabilities",
        "risk_agents",
        "risk_analytics",
    )
    lock = json.loads(
        (ROOT / "apps/portfolio-risk-workbench/risk-package-lock.json").read_text(encoding="utf-8")
    )
    assert tuple(sorted(lock["packages"])) == tuple(sorted(LOCAL_PACKAGE_NAMES))


def test_day1_host_adaptation_is_external_and_uses_the_day1_lock() -> None:
    source = (ROOT / "scripts/day1/bootstrap_servicefabric_runtime.py").read_text(encoding="utf-8")
    assert 'requirement_lock = REPOSITORY / "requirements" / "day1.lock"' in source
    assert "shutil.copytree" in source
    assert "risk-package-lock.json does not match reviewed Day 1 package sources" in source
