"""The finite Day 0 capability catalog."""

from .contracts import CapabilityDescriptor


ORDER_AND_BROKER_EFFECTS = (
    "order_submission",
    "broker_connectivity",
    "trade_execution",
    "automatic_rebalancing",
    "optimization",
    "hedge_execution",
    "provider_call",
    "external_llm_call",
)

CAPABILITY_DESCRIPTORS = (
    CapabilityDescriptor(capability_id="news.event.classify", objective="Classify an explicitly synthetic news event.", input_contract="NewsClassificationRequest with evidence.", output_contract="CapabilityResult containing synthetic classification.", denied_effects=ORDER_AND_BROKER_EFFECTS),
    CapabilityDescriptor(capability_id="alert.draft.synthesize", objective="Create a reviewable alert draft from supplied outputs.", input_contract="AlertSynthesisRequest with evidence.", output_contract="CapabilityResult containing AlertDraft.", denied_effects=ORDER_AND_BROKER_EFFECTS),
    CapabilityDescriptor(capability_id="alert.draft.review", objective="Record an explicit human decision on an alert draft.", input_contract="AlertReviewRequest with evidence.", output_contract="CapabilityResult containing DecisionPoint.", denied_effects=ORDER_AND_BROKER_EFFECTS),
    CapabilityDescriptor(
        capability_id="planning.knowledge.list_due",
        objective="List supplied deterministic planning products due by an explicit offset.",
        input_contract="KnowledgeDueRequest with evidence references.",
        output_contract="CapabilityResult containing due knowledge products.",
        allowed_effects=(),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="data.synthetic.ingest",
        objective="Expose a supplied local synthetic ingestion run without provider access.",
        input_contract="SyntheticIngestRequest with evidence references.",
        output_contract="CapabilityResult containing the supplied synthetic ingestion run.",
        allowed_effects=(),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="portfolio.snapshot.create",
        objective="Create an immutable portfolio snapshot from supplied normalized observations and positions.",
        input_contract="PortfolioSnapshotRequest with an explicit as_of timestamp and evidence references.",
        output_contract="CapabilityResult containing an immutable PortfolioSnapshot.",
        allowed_effects=(),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="portfolio.exposure.summarize",
        objective="Calculate a deterministic exposure summary from a supplied portfolio snapshot.",
        input_contract="ExposureSummaryRequest with evidence references.",
        output_contract="CapabilityResult containing an immutable ExposureSnapshot.",
        allowed_effects=(),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="market.anomaly.detect",
        objective="Detect threshold breaches in supplied synthetic market observations.",
        input_contract="AnomalyDetectionRequest with thresholds and evidence references.",
        output_contract="CapabilityResult containing an AnomalyReport.",
        allowed_effects=(),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.capability.news_sentiment",
        objective="Summarize supplied news evidence without fabricating observations.",
        input_contract="EvidenceReference[] and JSON-safe research context.",
        output_contract="CapabilityOutcome with preserved evidence references and disclosures.",
        allowed_effects=("draft_finding",),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.capability.market_data",
        objective="Describe supplied market-data evidence without fetching provider data.",
        input_contract="EvidenceReference[] and JSON-safe observation context.",
        output_contract="CapabilityOutcome with preserved evidence references and quality warnings.",
        allowed_effects=("draft_finding",),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.capability.portfolio_exposure",
        objective="Describe supplied portfolio exposure evidence without calculating analytics.",
        input_contract="EvidenceReference[] and JSON-safe snapshot context.",
        output_contract="CapabilityOutcome with preserved evidence references and limitations.",
        allowed_effects=("draft_finding",),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.capability.alert_recommendation",
        objective="Draft a review-required alert from supplied evidence; it is not investment advice.",
        input_contract="EvidenceReference[] and JSON-safe finding context.",
        output_contract="CapabilityOutcome with preserved evidence references and human-review disclosure.",
        allowed_effects=("draft_alert",),
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.returns.simple",
        objective="Calculate reviewed simple returns from supplied observations.",
        input_contract="ReturnsRequest with immutable prices and analysis evidence.",
        output_contract="CapabilityResult containing ReturnSeriesResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.returns.log",
        objective="Calculate reviewed logarithmic returns from supplied observations.",
        input_contract="ReturnsRequest with immutable prices and analysis evidence.",
        output_contract="CapabilityResult containing ReturnSeriesResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.volatility.annualized",
        objective="Calculate reviewed annualized sample volatility from supplied returns.",
        input_contract="VolatilityRequest with immutable returns and analysis evidence.",
        output_contract="CapabilityResult containing VolatilityResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.drawdown.maximum",
        objective="Calculate reviewed maximum drawdown from supplied returns.",
        input_contract="DerivedReturnsRequest with immutable returns and analysis evidence.",
        output_contract="CapabilityResult containing DrawdownResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.var.historical",
        objective="Calculate reviewed nearest-rank historical value at risk.",
        input_contract="HistoricalTailRiskRequest with immutable returns and analysis evidence.",
        output_contract="CapabilityResult containing HistoricalTailRiskResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.expected_shortfall.historical",
        objective="Calculate reviewed historical expected shortfall.",
        input_contract="HistoricalTailRiskRequest with immutable returns and analysis evidence.",
        output_contract="CapabilityResult containing HistoricalTailRiskResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.scenario.evaluate",
        objective="Evaluate a deterministic descriptive scenario from supplied shocks.",
        input_contract="ScenarioRequest with immutable portfolio, shocks, and analysis evidence.",
        output_contract="CapabilityResult containing ScenarioResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.contribution.summarize",
        objective="Summarize and reconcile supplied weighted return contributions.",
        input_contract="ContributionSummaryRequest with immutable values and analysis evidence.",
        output_contract="CapabilityResult containing ContributionSummary.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="risk.report.render",
        objective="Render evidence-backed Markdown and semantic HTML review material.",
        input_contract="ReportRequest containing one reviewed immutable analytics result.",
        output_contract="CapabilityResult containing RiskReport; human review is required.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="portfolio.data_context.create",
        objective="Create an exact-mapped point-in-time portfolio data context from supplied local immutable revisions.",
        input_contract="PortfolioDataContextCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing PortfolioDataContext.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="events.query.as_of",
        objective="Query one supplied immutable local event snapshot using available_at at an explicit as_of.",
        input_contract="EventQueryCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing EventQueryResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="monitoring.policy.evaluate",
        objective="Evaluate fixed reviewed monitoring thresholds without an expression language or scheduler.",
        input_contract="PolicyEvaluationCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing PolicyEvaluationResult.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="monitoring.alert.synthesize",
        objective="Synthesize an effect-free analytical alert draft from one completed fixed-policy evaluation.",
        input_contract="MonitoringAlertSynthesisCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing MonitoringAlertDraft.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="monitoring.run.contextual",
        objective="Run the existing four analytical roles against one point-in-time context and immutable policy revision.",
        input_contract="ContextualMonitoringCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing ContextualMonitoringRun.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="monitoring.report.render",
        objective="Render deterministic local Markdown and semantic HTML monitoring/replay review material.",
        input_contract="MonitoringReportCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing MonitoringReport.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="monitoring.replay",
        objective="Run deterministic historical monitoring steps with a fresh point-in-time context per step.",
        input_contract="ReplayCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing ReplayRun.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
    CapabilityDescriptor(
        capability_id="monitoring.evaluate",
        objective="Evaluate replay alerts with deterministic one-to-one labelled-outcome matching.",
        input_contract="ReplayEvaluationCapabilityRequest with evidence.",
        output_contract="CapabilityResult containing MonitoringEvaluation.",
        denied_effects=ORDER_AND_BROKER_EFFECTS,
    ),
)

CAPABILITY_BY_ID = {item.capability_id: item for item in CAPABILITY_DESCRIPTORS}
